// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: error_details.proto

package ngrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Source        *ErrorDetails_Source   `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails) Reset() {
	*x = ErrorDetails{}
	mi := &file_error_details_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails) ProtoMessage() {}

func (x *ErrorDetails) ProtoReflect() protoreflect.Message {
	mi := &file_error_details_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails.ProtoReflect.Descriptor instead.
func (*ErrorDetails) Descriptor() ([]byte, []int) {
	return file_error_details_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetails) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetails) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetails) GetSource() *ErrorDetails_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

type ErrorDetails_Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Traces        []string               `protobuf:"bytes,2,rep,name=traces,proto3" json:"traces,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetails_Source) Reset() {
	*x = ErrorDetails_Source{}
	mi := &file_error_details_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetails_Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetails_Source) ProtoMessage() {}

func (x *ErrorDetails_Source) ProtoReflect() protoreflect.Message {
	mi := &file_error_details_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetails_Source.ProtoReflect.Descriptor instead.
func (*ErrorDetails_Source) Descriptor() ([]byte, []int) {
	return file_error_details_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ErrorDetails_Source) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetails_Source) GetTraces() []string {
	if x != nil {
		return x.Traces
	}
	return nil
}

func (x *ErrorDetails_Source) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_error_details_proto protoreflect.FileDescriptor

const file_error_details_proto_rawDesc = "" +
	"\n" +
	"\x13error_details.proto\x12\x05ngrpc\"\xb0\x02\n" +
	"\fErrorDetails\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x06source\x18\x03 \x01(\v2\x1a.ngrpc.ErrorDetails.SourceR\x06source\x1a\xbd\x01\n" +
	"\x06Source\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06traces\x18\x02 \x03(\tR\x06traces\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.ngrpc.ErrorDetails.Source.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x19Z\x17github.com/nbs-go/ngrpcb\x06proto3"

var (
	file_error_details_proto_rawDescOnce sync.Once
	file_error_details_proto_rawDescData []byte
)

func file_error_details_proto_rawDescGZIP() []byte {
	file_error_details_proto_rawDescOnce.Do(func() {
		file_error_details_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_error_details_proto_rawDesc), len(file_error_details_proto_rawDesc)))
	})
	return file_error_details_proto_rawDescData
}

var file_error_details_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_error_details_proto_goTypes = []any{
	(*ErrorDetails)(nil),        // 0: ngrpc.ErrorDetails
	(*ErrorDetails_Source)(nil), // 1: ngrpc.ErrorDetails.Source
	nil,                         // 2: ngrpc.ErrorDetails.Source.MetadataEntry
}
var file_error_details_proto_depIdxs = []int32{
	1, // 0: ngrpc.ErrorDetails.source:type_name -> ngrpc.ErrorDetails.Source
	2, // 1: ngrpc.ErrorDetails.Source.metadata:type_name -> ngrpc.ErrorDetails.Source.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_error_details_proto_init() }
func file_error_details_proto_init() {
	if File_error_details_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_error_details_proto_rawDesc), len(file_error_details_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_details_proto_goTypes,
		DependencyIndexes: file_error_details_proto_depIdxs,
		MessageInfos:      file_error_details_proto_msgTypes,
	}.Build()
	File_error_details_proto = out.File
	file_error_details_proto_goTypes = nil
	file_error_details_proto_depIdxs = nil
}
